### PR TITLE
Include surface_name in information send to mod interfaces

### PR DESCRIPTION
**Pull request by Afforess**
Necessary to support multi-surface games.

### CODE REVIEW

**Comment by narc0tiq** [comment]
I see where you're going with this, but I was expecting to use the player's surface, as [the demonstrator does](https://github.com/narc0tiq/WrenchFu-Demo/blob/master/control.lua#L8). I'm not sure by what process a player could tap a wrench on a machine on a surface other than the one they're standing on.

**Comment by Afforess** [comment]
@narc0tiq I assume you are referring to `v.surface.name`? It should always be identical to player.surface.name, because that is the surface you used to search with find_entities. I can update the PR to make that clearer, but functionally, it is correct.

Edit: Oh, it appears you meant the mods should be able to use `player.surface` to find the correct surface. I think that is correct 99.999% of the time, and I hadn't considered that. For correctness sake, the player could theoretically be teleported to a new surface, while the entity that owns the GUI would not be. If you don't think this particular case is worth handling (and it probably is not), then I can close the PR and just use the `player.surface`.

**Comment by narc0tiq** [comment]
Sorry, I was unclear.

WrenchFu already passes along a `player_index` to the remote interface, to allow the remote mod to open its GUI to the right person. Since the remote mod has that, it can (currently) also assume the target entity is present on the player's surface. In what circumstance is this assumption faulty?

**Comment by Afforess** [comment]
@narc0tiq see my edit: https://github.com/narc0tiq/WrenchFu/pull/3#issuecomment-170435923

**Comment by Afforess** [comment]
After consideration, I do agree using `player.surface` should be fine. Any chance of an update of WrenchFu on the factorio forums with the 0.12.11 compatible release?

**Comment by narc0tiq** [comment]
Can do. Look for it in the next couple of hours (I need to be on the way to work soon, but I'll get to it from work if need be).

There's one thing that comes to mind with regards to a multi-surface game: if the player is teleported to a new surface while a WrenchFu GUI is open and their position in the new surface is not too far off their position in the old surface, the GUI won't be closed by the on_tick handler. I'm not sure this will come up very often in a real game, but it's still a possible issue.

If you feel like fixing it, it's probably just a matter of passing the surface to `WrenchFu.open_gui_at`, which would store the surface in `global.open_guis[player_index].surface`, and adding a same-surface check in `WrenchFu.on_tick`.

**Pull request closed without merging**
